# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  Docker:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]
          java: [8]
      steps:
      - name: "Login to Docker Registry"
        uses: docker/login-action@v2
        with:
          registry: release.daocloud.io
          username: ${{ secrets.DAOCLOUD_REGISTRY_USERNAME }}
          password: ${{ secrets.DAOCLOUD_REGISTRY_PWD }}
